#:schema node_modules/wrangler/config-schema.json
name = "lg-optics-landing"
main = ".open-next/worker.js"
compatibility_date = "2024-10-31"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "lg-optics-cache"
preview_bucket_name = "lg-optics-cache-preview"

[[env.production.vars]]

[[env.dev.vars]]